### PR TITLE
Session on the paiement server is different that the user one

### PR DESCRIPTION
**Pull request by titoff3**
Session on the payment server is different than the user one so when the server checks the order in session, the order can't get retrieved.

List of modifications :
- Class refactoring, 
- Delete duplicated code,
- Add cancel routing process,
- No more use of session to store the sips entity. Now using request forward from the JRK to the custom controller with the payment response in parameter.

### CODE REVIEW

**Comment by jr-k** [comment]
Line 227 in Controller there is a `//@@ TODO : virer ou corriger le cancel` can you update it please ?

Is readme up to date with your modifications ?

Thanks.

**Comment by titoff3** [comment]
Hello,

Sorry, at the start, I didn’t want to implement the cancel but in fact I did it.
The readme isn’t up to date.
Do you want I take a look ?

Thanks.

**Comment by jr-k** [comment]
No problem, well done.

For the readme, yes please, you're the chosen one :tada:

**Comment by titoff3** [comment]
Ok i’ll try to make something clear for everyone ;-)

**Comment by titoff3** [comment]
Hello, 

If you can take a look to the readme, I hope it’s good for you.

Thanks ;-).

**Pull request merged**
